# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b7116850b900b3d51d05a6475e6a808aa603d428938d1f708609cd6b723e494a622078655d177e0e0eff8fb47cad55c3679b230ca9905996d4d5d857594ce99

test:
  secret_key_base: 4cd0ba91fa781df4c0c1b8681db9072f4bbb38ea0486742932165bfc804a3c99add10f454a08ff70e170d877da07033e9a3b88d4b71309e7bee32a3ff166181a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
